apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1-hello
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1-hello
  template:
    metadata:
      labels:
        app: app1-hello
    spec:
      containers:
        - name: app1-hello
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app1-hello
spec:
  selector:
    app: app1-hello
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 80
